In [13]:
import json
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import nltk

In [3]:
data = pd.read_json('https://raw.githubusercontent.com/risan/quran-json/master/json/translations/en.pretty.json')

In [4]:
data

,surah_number,verse_number,content
0,1,1,"In the name of Allah, the Entirely Merciful, t..."
1,1,2,"[All] praise is [due] to Allah, Lord of the wo..."
2,1,3,"The Entirely Merciful, the Especially Merciful,"
3,1,4,Sovereign of the Day of Recompense.
4,1,5,It is You we worship and You we ask for help.
...,...,...,...
6231,114,2,The Sovereign of mankind.
6232,114,3,"The God of mankind,"
6233,114,4,From the evil of the retreating whisperer -
6234,114,5,Who whispers [evil] into the breasts of mankind -
6235,114,6,"From among the jinn and mankind."""

In [5]:
data.drop(['surah_number'],axis=1,inplace=True)

In [6]:
data

      verse_number                                            content
0                1  In the name of Allah, the Entirely Merciful, t...
1                2  [All] praise is [due] to Allah, Lord of the wo...
2                3    The Entirely Merciful, the Especially Merciful,
3                4                Sovereign of the Day of Recompense.
4                5      It is You we worship and You we ask for help.
...            ...                                                ...
6231             2                          The Sovereign of mankind.
6232             3                                The God of mankind,
6233             4        From the evil of the retreating whisperer -
6234             5  Who whispers [evil] into the breasts of mankind -
6235             6                  From among the jinn and mankind."

[6236 rows x 2 columns]

In [7]:
data.describe()

       verse_number
count   6236.000000
mean      53.506575
std       50.463924
min        1.000000
25%       16.000000
50%       38.000000
75%       75.000000
max      286.000000

In [8]:
data.head(27)

    verse_number                                            content
0              1  In the name of Allah, the Entirely Merciful, t...
1              2  [All] praise is [due] to Allah, Lord of the wo...
2              3    The Entirely Merciful, the Especially Merciful,
3              4                Sovereign of the Day of Recompense.
4              5      It is You we worship and You we ask for help.
5              6                    Guide us to the straight path -
6              7  The path of those upon whom You have bestowed ...
7              1                                   Alif, Lam, Meem.
8              2  This is the Book about which there is no doubt...
9              3  Who believe in the unseen, establish prayer, a...
10             4  And who believe in what has been revealed to y...
11             5  Those are upon [right] guidance from their Lor...
12             6  Indeed, those who disbelieve - it is all the s...
13             7  Allah has set a seal upon their hearts and upo...
14             8  And of the people are some who say, "We believ...
15             9  They [think to] deceive Allah and those who be...
16            10  In their hearts is disease, so Allah has incre...
17            11  And when it is said to them, "Do not cause cor...
18            12  Unquestionably, it is they who are the corrupt...
19            13  And when it is said to them, "Believe as the p...
20            14  And when they meet those who believe, they say...
21            15  [But] Allah mocks them and prolongs them in th...
22            16  Those are the ones who have purchased error [i...
23            17  Their example is that of one who kindled a fir...
24            18  Deaf, dumb and blind - so they will not return...
25            19  Or [it is] like a rainstorm from the sky withi...
26            20  The lightning almost snatches away their sight...

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6236 entries, 0 to 6235
Data columns (total 2 columns):
verse_number    6236 non-null int64
content         6236 non-null object
dtypes: int64(1), object(1)
memory usage: 97.6+ KB